# Generated by Django 5.0.7 on 2024-09-18 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_alter_auctionlisting_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 16, 26, 19, 401748, tzinfo=datetime.timezone.utc)),
        ),
    ]
