# Generated by Django 5.0.7 on 2024-09-18 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_alter_auctionlisting_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 17, 41, 49, 457265, tzinfo=datetime.timezone.utc)),
        ),
    ]
