# Generated by Django 5.0.7 on 2024-09-19 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_alter_auctionlisting_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 6, 44, 53, 936888, tzinfo=datetime.timezone.utc)),
        ),
    ]
