# Generated by Django 5.0.7 on 2024-09-19 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_alter_auctionlisting_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 10, 11, 32, 731065, tzinfo=datetime.timezone.utc)),
        ),
    ]
